### ISSUE TITLE
Error when pulling item list

### ISSUE THREAD

**Issue by Tellik** [maruohon/tellme#10]
/tellme dump items -> An unknown error occurred while attempting to perform this command.

Seems to occur when using NotEnoughIDs to extend available item IDs past 32767.

**Comment by Tellik** [comment]
This is the error it's giving specifically, I forgot to check the log before.

`[17:43:34] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: tellme list items dump
java.lang.NullPointerException: null
	at com.elytradev.architecture.common.shape.ItemShape.func_150895_a(ItemShape.java:118) ~[ItemShape.class:?]
	at fi.dy.masa.tellme.proxy.ClientProxy.getDataForItemSubtypes(ClientProxy.java:91) ~[ClientProxy.class:?]
	at fi.dy.masa.tellme.datadump.ItemDump.getFormattedItemDump(ItemDump.java:86) ~[ItemDump.class:?]
	at fi.dy.masa.tellme.command.SubCommandDump.getData(SubCommandDump.java:179) ~[SubCommandDump.class:?]
	at fi.dy.masa.tellme.command.SubCommandDump.outputData(SubCommandDump.java:99) ~[SubCommandDump.class:?]
	at fi.dy.masa.tellme.command.SubCommandDump.execute(SubCommandDump.java:90) ~[SubCommandDump.class:?]
	at fi.dy.masa.tellme.command.CommandTellme.func_184881_a(CommandTellme.java:85) ~[CommandTellme.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[17:43:34] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] An unknown error occurred while attempting to perform this command`

And yes, NEID was added because it ran out of available IDs.

**Comment by maruohon** [comment]
This build should fix the crash: https://pena2.dy.fi/tmp/minecraft/mods/tellme/tellme-1.12.2-0.6.0-dev.20180416.040221.jar

Let me know if it works or not.

**Comment by Tellik** [comment]
Yup, that works great.

Looks like I had about 67136 items total in it.

https://gyazo.com/c998aeddb74ddf95f86e158659204324

Also, I noticed a few weird characters, which appear to be color codes. It's not a big issue but if there was a way to strip them out sometime (when you got around to it) that'd be cool.

**Comment by maruohon** [comment]
Does this build properly strip away the formatting codes in your case? https://pena2.dy.fi/tmp/minecraft/mods/tellme/tellme-1.12.2-0.6.0-dev.20180416.050059.jar
