### ISSUE TITLE
NPE on dumping enchantments

### ISSUE THREAD

**Issue by LemADEC** [maruohon/tellme#13]
As of 1.12.2-0.6.0, dumping enchantments fails:
```
[18:54:40] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: tellme dump-csv all
java.lang.NullPointerException: null
	at fi.dy.masa.tellme.datadump.EnchantmentDump.getFormattedEnchantmentDump(EnchantmentDump.java:28) ~[EnchantmentDump.class:?]
	at fi.dy.masa.tellme.command.SubCommandDump.getData(SubCommandDump.java:149) ~[SubCommandDump.class:?]
	at fi.dy.masa.tellme.command.SubCommandDump.outputData(SubCommandDump.java:111) ~[SubCommandDump.class:?]
	at fi.dy.masa.tellme.command.SubCommandDump.execute(SubCommandDump.java:94) ~[SubCommandDump.class:?]
	at fi.dy.masa.tellme.command.CommandTellme.func_184881_a(CommandTellme.java:92) ~[CommandTellme.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:88) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by maruohon** [comment]
I just recently fixed this crash, but haven't pushed that commit yet...
I'll try to get a new release out with the fix in the coming days, I just need to implement one new dump type before that.

**Comment by maruohon** [comment]
Dev build here with the fix: https://masa.dy.fi/tmp/minecraft/mods/tellme/tellme-1.12.2-0.7.0-dev.20181107.012547.jar
