### ISSUE TITLE
Not possible to run /tellme locate in the console

### ISSUE THREAD

**Issue by zwamdurkel** [maruohon/tellme#30]
There is to my knowledge no way to run these commands in the console, because a dimension is required but I do not know how to provide it.

This is the result when trying to run the command:
```
tellme locate block to-console simple all-loaded-chunks minecraft:oak_log
[19:32:47] [Server thread/INFO] [minecraft/DedicatedServer]: This command must either be executed by an entity, or the dimension must be specified
```

I should clarify that I'm using Forge 1.18

**Comment by maruohon** [comment]
You need to specify the dimension if you run it via the console. I think the dimension would be the last argument? (You can check in single player with the command suggestions what the argument order is.)

**Comment by zwamdurkel** [comment]
So this time I tried to run the same command as a player, then this happened. Also there was no option for a dimension, I do recall that being an option in older version (all-dims etc.)

```
[19:55:01] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IncompatibleClassChangeError: Found interface net.minecraft.core.RegistryAccess, but class was expected
        at fi.dy.masa.tellme.util.WorldUtils.getDimensionId(WorldUtils.java:48) ~[tellme-forge-1.18.1-0.10.0%20(1).jar%2339!/:0.10.0] {re:classloading}
        at fi.dy.masa.tellme.util.chunkprocessor.LocateBlocks.processChunks(LocateBlocks.java:103) ~[tellme-forge-1.18.1-0.10.0%20(1).jar%2339!/:0.10.0] {re:classloading}
        at fi.dy.masa.tellme.util.chunkprocessor.ChunkProcessorAllChunks.processChunks(ChunkProcessorAllChunks.java:63) ~[tellme-forge-1.18.1-0.10.0%20(1).jar%2339!/:0.10.0] {re:classloading}
        at fi.dy.masa.tellme.command.SubCommandLocate.locate(SubCommandLocate.java:112) ~[tellme-forge-1.18.1-0.10.0%20(1).jar%2339!/:0.10.0] {re:classloading}
        at fi.dy.masa.tellme.command.SubCommandLocate.lambda$createNodes$2(SubCommandLocate.java:70) ~[tellme-forge-1.18.1-0.10.0%20(1).jar%2339!/:0.10.0] {re:classloading}
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%2324!/:?] {}
        at net.minecraft.commands.Commands.m_82117_(Commands.java:234) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1150) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1129) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1115) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:30) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:7) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
 ```
[crash-2022-08-20_19.55.01-server.txt](https://github.com/maruohon/tellme/files/9387793/crash-2022-08-20_19.55.01-server.txt)

**Comment by maruohon** [comment]
Oh you are in MC 1.18.2. Looks like I haven't released a 1.18.2 Forge version of TellMe yet, and there were a lot of vanilla changes from 1.18.1, so that mod version will crash in a bunch of places when used in 1.18.2.

**Comment by zwamdurkel** [comment]
Oh you are totally right! I did not notice that 1.18.2 wasn't supported, sorry for wasting your time. 

But I would really like to use your tool to locate a block that is lagging a server of mine, I just don't know where it is, so I'm looking forward to the 1.18.2 release

**Comment by mjevans** [comment]
I just encountered this same issue while trying to dump biomes...

It seems to crash even while trying to dump a simple list of tags-item-split that have ores. : ( that's the one I really wanted.

**Comment by mjevans** [comment]
Additionally: ADDING this mod, doing nothing else with it at all, causes strange rendering issues for at least Tinker's Construct.

I'm amazed there's any graphical component at all, and that a 1.18.2 version is that badly needed.

**Comment by maruohon** [comment]
The 1.18.1 version will crash in 1.18.2 if you do anything that touches biomes or tags, as those things changed in vanilla between those versions. I was supposed to make the 1.18.2 port today but didn't have time... maybe towards the weekend.

As for graphical issue... that doesn't make any sense. There are no graphics related things in TellMe. Unless some of the vanilla code change related things/version incompatibilities breaks loading some classes which then breaks parts of the game.

**Comment by mjevans** [comment]
I agree, it probably breaks some other classes loading and that's likely what causes the render breaks.

Hopefully the issues are all resolved by a 1.18.2 version.
